name: Hello world workflow
on: [push]

jobs:
  start:
    name: File start
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: echo Test > hello.txt
  list:
    name: List files
    runs-on: ubuntu-latest
    needs: start
    steps:
      - name: List
        run: ls
  echo:
    name: Echo file
    runs-on: ubuntu-latest
    needs: start
    steps:
      - name: Echo
        run: cat hello.txt
