name: Hello world workflow
on: [push]

jobs:
  build:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
      - name: Echo hello world
        run: echo 'Hello world'
  test:
    name: Test some shit
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Always fail
        run: false
  final:
    name: Never run
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Never
        run: echo gonna wake up
